cats_auth_99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session, only: [:new, :create, :destroy] 
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end

  end

  root to: redirect('/cats')
end

cats_auth_99/app/models/user.rb
class User < ApplicationRecord
  validates :user_name, :password_digest, presence: true, uniqueness: true
  validates :session_token, uniqueness: true
  
  after_initialize do |user|
    self.session_token ||= User.generate_token
  end
  
  def self.generate_token
    SecureRandom.urlsafe_base64
  end
  
  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    if user &&  is_password?(password)
      user
    else
      nil
    end
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
  
  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    user = User.find_by(user_name: self.user_name)
    
    BCrypt::Password.new(user.password_digest) == password
  end
  
end

cats_auth_99/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.all.first 
    render :new
  end
  
  def create
    user = User.create(user_params)
    login(user)
    if user.save!
      redirect_to user_url(user)
    end
  end
  
  def show
    @user = User.find(params[:id])
    render :show
  end
  
  private
  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

cats_auth_99/app/views/users/_new_form.html.erb
<% if @user.logged_in? %>
  <% action_type = users_url(@user) %>
  <% submit_value = "Sign Up" %>
<% else %>
  <% action_type = session_url %>
  <% submit_value %>
<form action="<%= users_url(@user) %>" method="post">
Username: 
<input type="text" name="user[user_name]" value="">
<br>
Password: 
<input type="text" name="user[password]" value="">
<br>
<input type="submit" name="" value=<%= submit_value %>>
</form>

cats_auth_99/app/views/users/new.html.erb
<%= render 'new_form', action: users_url%>

cats_auth_99/app/views/users/show.html.erb
<br />
<marquee behavior="scroll" direction="right" scrollamount=100><%= @user.user_name %></marquee>
<br />
<marquee behavior="scroll" direction="left" scrollamount=10> <%= @user.password_digest %> </marquee>
<br />
<marquee behavior="scroll" direction="right" scrollamount=10><%= @user.user_name %></marquee>
<br />
<marquee behavior="scroll" direction="left" scrollamount=30> <%= @user.password_digest %> </marquee>
<br />
<marquee behavior="scroll" direction="right" scrollamount=10><%= @user.user_name %></marquee>
<br />
<marquee behavior="scroll" direction="left" scrollamount=5> <%= @user.password_digest %> </marquee>
<br />
<marquee behavior="scroll" direction="right" scrollamount=10><%= @user.user_name %></marquee>
<br />
<marquee behavior="scroll" direction="left" scrollamount=10 > <%= @user.password_digest %> </marquee>
<br />
<marquee behavior="scroll" direction="right" scrollamount=17><%= @user.user_name %></marquee>
<br />
<marquee behavior="scroll" direction="left" scrollamount=10> <%= @user.password_digest %> </marquee>
<br />
<marquee behavior="scroll" direction="right" scrollamount=90><%= @user.user_name %></marquee>
<br />
<marquee behavior="scroll" direction="left" scrollamount=18> <%= @user.password_digest %> </marquee>
<br />
<marquee behavior="scroll" direction="right" scrollamount=2><%= @user.user_name %></marquee>
<br />
<marquee behavior="scroll" direction="left" scrollamount=10> <%= @user.password_digest %> </marquee>
<br />
<marquee behavior="scroll" direction="right" scrollamount=10 ><%= @user.user_name %></marquee>
<br />
<marquee behavior="up" direction="left" scrollamount=70 style="text-align: vertical">  <%= @user.password_digest %> </marquee>
<br />
<marquee behavior="scroll" direction="right" scrollamount=10><%= @user.user_name %></marquee>
<br />
<marquee behavior="scroll" direction="left" scrollamount=14> <%= @user.password_digest %> </marquee>
<br />
<marquee behavior="scroll" direction="right" scrollamount=10><%= @user.user_name %></marquee>
<br />
<marquee behavior="scroll" direction="left" scrollamount=10> <%= @user.password_digest %> </marquee>
<br />
<marquee behavior="scroll" direction="right" scrollamount=12><%= @user.user_name %></marquee>
<br />
<marquee behavior="scroll" direction="left" scrollamount=10> <%= @user.password_digest %> </marquee>
<br />
<marquee behavior="scroll" direction="right" scrollamount=10><%= @user.user_name %></marquee>
<br />
<marquee behavior="scroll" direction="left" scrollamount=1> <%= @user.password_digest %> </marquee>